version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Dependencies installation started"
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - echo "Verifying Flask installation"
      - python3 -c "import flask; print('Flask version:', flask.__version__)"
  
  pre_build:
    commands:
      - echo "Pre-build phase started"
      - echo "Checking Python syntax"
      - python3 -m py_compile web.py
      - python3 -m py_compile scripts/*.py
      - echo "Syntax check completed"
  
  build:
    commands:
      - echo "Build started"
      - echo "Running application tests"
      - python3 test_app.py
      - echo "Tests completed successfully"
      - echo "Making scripts executable"
      - chmod +x scripts/*.sh
      - chmod +x scripts/*.py
  
  post_build:
    commands:
      - echo "Post-build phase started"
      - echo "Build completed successfully"
      - ls -la
      - echo "Listing scripts directory:"
      - ls -la scripts/

artifacts:
  files:
    - web.py
    - test_app.py
    - requirements.txt
    - appspec.yml
    - templates/**/*
    - scripts/**/*
  name: flask-web-app
